# Generated by Django 2.0.2 on 2018-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsId', models.BigAutoField(primary_key=True, serialize=False)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
    ]
