# Generated by Django 2.0.2 on 2018-07-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
